### PR TITLE
new features

### PR DESCRIPTION
**Pull request by xKumorio**
www

### CODE REVIEW

**Comment by hungnguyennaz** [comment]
Should i rename NeonPaper to Yatopia?

**Comment by xKumorio** [comment]
> Should i rename NeonPaper to Yatopia?

What? Why? Does it matter what it's called or how the comments are signed? I'm making it easier to find what I changed earlier in case there's a problem.

**Comment by xKumorio** [comment]
The main thing is that it works.
image

**Comment by xKumorio** [comment]
Well, if you want, I'll do it. Do you need it?

**Pull request merged**
